### ISSUE TITLE
Magus:  Can't exec "getseq" at PATH/Magus/Magus.pm line 64 

### ISSUE THREAD

**Issue by HmuSong** [institut-de-genomique/MaGuS#2]
Hello, 
      when I used the Magus pairs2links function to estimate the gaps size between two scaffold, I have encounted this problem  that _Can't exec "getseq": at PATH/Magus/Magus.pm line 64 [ERROR] :: fill :: Cannot use getseq : _. I have searched the entire file but could not find the sub function "getseq". Could you tell me the reason why this error occured? Thank very much!

**Comment by cdossat** [comment]
Hello,
getseq is not a sub function, it's a stand-alone program which is provided in bin/ directory.
Have you added MaGuS binaries in $PATH ?

**Comment by HmuSong** [comment]
Hello,
I have checked my $PATH, the problem just like you said. The issue have been solved and MaGus works well now. Thanks a lot for your  help.  I got the results of pairs2links now, but I can't understand the meaning of each column of the "*******.de" file.

**Comment by leo-dagata** [comment]
Hello,
The format of .de file belongs to SGA program that you can find in the following link: https://github.com/jts/sga
Fortunatly, you can learn more about .de format by reading this google group:
https://groups.google.com/forum/#!topic/sga-users/7a01mz_ObTE

**Comment by HmuSong** [comment]
Thank you very much for your guide.
